### ISSUE TITLE
Range check error in TSequenceModel.GetOrder

### ISSUE THREAD

**Issue by MShark67** [ms301/charset-enigma#2]
When detecting the encoding of the test files in the data directory several of the files cause the above error.

The offending line seems to be:
    Result := FCharToOrderMap[b]
where b is outside the size of the CharToOrderMap array.

My quick and dirty fix was to change the function as follows:

  if b < Length(FCharToOrderMap) then
    Result := FCharToOrderMap[b]
  else
    Result := 0;

Cool project!  Note that I hit several more range check errors, so turning on range checking while testing might help pinpoint some issues.

**Comment by rareMaxim** [comment]
Thanks. Closed in 3c142c8
